### ISSUE TITLE
LUA error since 10.0.0 patch - nil 'entry' at 302

### ISSUE THREAD

**Issue by raysmith59** [GreenhairTurtle/ImprovedAddonList#1]
I just picked up this addon, I have so many addons that are still out of date and slowly being updated that I wanted more control over the loadout so was hoping this would help with my troubleshooting.  However, when I log in I'm getting the error below.  I tried protecting against nils in the function call (that and the other function that took an 'entry' parameter) which allowed the addon to load without error but I'm getting a new error when I try to save to a new layout, I'll report that separately.  I'll poke around a bit more to see if I can make it functional but I'm guessing there's more wrong after the patch than I'll be able to fix.

I also have no idea why there'd be a nil result in the addon list, could be an in-game bug.

1x ...rface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:302: attempt to index local 'entry' (a nil value)
[string "@Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua"]:302: in function `ShowMemoryUsage'
[string "@Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua"]:295: in function <...rface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:282>
[string "=[C]"]: in function `AddonList_Update'
[string "@Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua"]:227: in function `RefreshDropDownAndList'
[string "@Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua"]:220: in function `InitUI'
[string "@Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua"]:116: in function <...rface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:112>
[string "=(tail call)"]: ?

Locals:
self = <table> {
 GetAllAddons = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:560
 OnAddonTooltipUpdate = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:238
 OnAddonListShow = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:231
 OnConfigurationSelected = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:167
 ResetAll = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:127
 IsConfigurationGlobal = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:541
 PLAYER_FLAGS_CHANGED = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:206
 OnAddonListUpdate = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:282
 OnInputDialogConfirm = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:414
 CheckConfigurationCondition = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:393
 CheckDistinct = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:536
 ShowError = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:24
 ShowConfigurationSwitchPromptDialog = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:468
 DeleteConfiguration = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:385
 ResetConfiguration = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:361
 ExportAddonListWithBBSCode = <function> defined @Interface/AddOns/ImprovedAddonList/Export.lua:14
 GetPlayerInfos = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:224
 LastUpdateMemoryUsageTime = 66563.265000
 OnDropDownMenuInitialize = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:158
 GetExportAddonData = <function> defined @Interface/AddOns/ImprovedAddonList/Export.lua:147
 CreateExportDialog = <function> defined @Interface/AddOns/ImprovedAddonList/Export.lua:98
 ExportAddonListWithMarkDown = <function> defined @Interface/AddOns/ImprovedAddonList/Export.lua:61
 Frame = Frame {
 }
 ExportAddonList = <function> defined @Interface/AddOns/ImprovedAddonList/Export.lua:4
 ShowOrHideInputDialog = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:394
 ShowRemark = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:319
 IsCurrentConfiguration = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:570
 ADDON_LOADED = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:112
 OnTipsButtonClick = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:339
 GetEnabledAddons = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:547
 GetConfiguration = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:594
 IsConfigurationMeetCondition = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:376
 ShowMemoryUsage = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:301
 SaveConfiguration = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:344
 PLAYER_LOGIN = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:174
 GetConfigurationWithConditions = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:346
 MustbeSaveToGlobal = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:287
 GetClassAndSpecInfos = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:237
 InitConditionContent = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:211
 PLAYER_SPECIALIZATION_CHANGED = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:199
 PLAYER_ENTERING_WORLD = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:195
 ResetConditions = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:362
 GetConfigurations = <f

**Comment by KittenBall** [comment]
Blz change the scrollview construct method  which is addonlist used,  I won't fix it, Instead, I think a whole new addon panel which no taint, more features will better to use. This issue will be closed when a new version arrives.

**Comment by JumpyCraft** [comment]
What will the new addon be called

**Comment by KittenBall** [comment]
> What will the new addon be called

The same name, not a new addon. For now, just disable this addon. I'm sorry.

**Comment by raysmith59** [comment]
For what it's worth I've been using the addon with the workarounds I mentioned without any issue so far, it's working fine for what I need it for.

**Comment by KittenBall** [comment]
> 

Well, I temporarily disabled remark and export features, and it shouble be work fine in 1.9.11

**Comment by KittenBall** [comment]
fix by v2.0.0, which is a completely reworked version
