### ISSUE TITLE
LUA error since 10.0.0 patch - nil 'TitleText' at 404 (406 in mine)

### ISSUE THREAD

**Issue by raysmith59** [GreenhairTurtle/ImprovedAddonList#2]
After hopefully working around the nil 'entry' issue from the other report, I tried saving a new layout and got this error.  In the original code it would be line 404 but it's 406 in mine due to the two lines I added to avoid nils in the other scenario.

For this one, commenting out the two .TitleText:SetText lines seems to work and just displays the dialog without the title, possibly TitleText requires explicit declaration now or something if it didn't before?

2x ...rface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:406: attempt to index field 'TitleText' (a nil value)
[string "@Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua"]:406: in function `ShowOrHideInputDialog'
[string "@Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua"]:383: in function <...rface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:373>

Locals:
self = <table> {
 GetAllAddons = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:562
 OnAddonTooltipUpdate = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:238
 OnAddonListShow = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:231
 OnConfigurationSelected = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:167
 ResetAll = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:127
 IsConfigurationGlobal = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:543
 PLAYER_FLAGS_CHANGED = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:206
 OnAddonListUpdate = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:282
 OnInputDialogConfirm = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:416
 CheckConfigurationCondition = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:393
 CheckDistinct = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:538
 ShowError = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:24
 ShowConfigurationSwitchPromptDialog = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:468
 DeleteConfiguration = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:387
 ResetConfiguration = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:363
 ExportAddonListWithBBSCode = <function> defined @Interface/AddOns/ImprovedAddonList/Export.lua:14
 GetPlayerInfos = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:224
 LastUpdateMemoryUsageTime = 67065.744000
 OnDropDownMenuInitialize = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:158
 GetExportAddonData = <function> defined @Interface/AddOns/ImprovedAddonList/Export.lua:147
 CreateExportDialog = <function> defined @Interface/AddOns/ImprovedAddonList/Export.lua:98
 ExportAddonListWithMarkDown = <function> defined @Interface/AddOns/ImprovedAddonList/Export.lua:61
 Frame = Frame {
 }
 ExportAddonList = <function> defined @Interface/AddOns/ImprovedAddonList/Export.lua:4
 ShowOrHideInputDialog = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:396
 ShowRemark = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:321
 IsCurrentConfiguration = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:572
 ADDON_LOADED = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:112
 OnTipsButtonClick = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:341
 GetEnabledAddons = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:549
 GetConfiguration = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:596
 IsConfigurationMeetCondition = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:376
 ShowMemoryUsage = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:303
 SaveConfiguration = <function> defined @Interface/AddOns/ImprovedAddonList/ImprovedAddonList.lua:346
 PLAYER_LOGIN = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:174
 GetConfigurationWithConditions = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:346
 MustbeSaveToGlobal = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:287
 GetClassAndSpecInfos = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:237
 InitConditionContent = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:211
 PLAYER_SPECIALIZATION_CHANGED = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:199
 PLAYER_ENTERING_WORLD = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:195
 ResetConditions = <function> defined @Interface/AddOns/ImprovedAddonList/Condition.lua:362
 GetConfigurations = <f

**Comment by KittenBall** [comment]
Same witch #1 , for now, It is recommended that you temporarily disable this addon
